jwt.secret: 7h1nkm1cr053rv1c35
controller.cors.origin: http://localhost:8080
 
  
    
management:
  endpoints:
    metrics:
      sensitive: false
    web:
      exposure:
        include: info,health,prometheus
        
management.metrics.tags.application: ${spring.application.name}     
    

 


 
 
